inherit_from: "configs/rgbd/otto/base_config.yaml"

Dataset:
  dataset_path: "/ssd/monogs/datasets/otto/vivaio_1"
  Calibration:
    fx: 906.4804077148438
    fy: 906.260498046875
    cx: 968.183349609375
    cy: 547.8143310546875
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    distorted: False
    width: 1920
    height: 1080
    depth_scale: 1000.0
